### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by elir0d** [roelisontrindade/Build-a-Survey-Form#18]
- [x] Preencher todos os nomes e atributos relacionados ao HTML

- [x] Testar o formulário com o Test Suite do FCC
- [x] Refatorar as classes e IDs.

- [x] Definir os arquivo CSS e trabalhar na estilização da página

**Comment by cassiorsfreitas** [comment]
Fala, @roelisontrindade , beleza? Coloca aqui o layout final da página pra facilitar a contribuição dessa última task.
